train_config :
  batch_size: 32
  max_epochs: 10
  fine_tune: 0
  learning_rate: 0.0001

model_config :
  bert_path:
    bert_base_chinese: ../bert_base_chinese
  dropout_prob: 0.5
  hidden_size: 200





